name: PR-Whisperer-AI

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  generate-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AI PR Describer
        uses: viniciustakedi/PR-Whisperer-AI@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
